/*******************************************************************************
 *  Pickering Switching (pilpxi) functions IDs
 *
 *  Copyright (C) 1988 - 2011, Pickering Interfaces ltd.
 *  
 *  Author: michal.heczko
 *  Contact: michal.heczko@pickeringmail.cz
 *  
 *******************************************************************************/

#ifndef _PIPLXFIDS_H_
#define _PIPLXFIDS_H_

enum PilPxiFunctionIDs {
	PIPLX_FID_CARDID	= 0x00010000,
  PIPLX_FID_CARDLOC,
  PIPLX_FID_CARDOPSCOUNT,
  PIPLX_FID_CLEARALL,
  PIPLX_FID_CLEARCARD,
  PIPLX_FID_CLEARMASK,
  PIPLX_FID_CLEARSUB,
  PIPLX_FID_CLOSECARDS,
  PIPLX_FID_CLOSESPECIFIEDCARD,
  PIPLX_FID_CLOSURELIMIT,
  PIPLX_FID_DIAGNOSTIC,
  PIPLX_FID_ENUMERATESUBS,
  PIPLX_FID_MASKBIT,
  PIPLX_FID_MASKCROSSPOINT,
  PIPLX_FID_OPBIT,
  PIPLX_FID_OPCROSSPOINT,
  PIPLX_FID_OPENCARDS,
  PIPLX_FID_OPENSPECIFIEDCARD,
  PIPLX_FID_READBIT,
  PIPLX_FID_READCAL,
  PIPLX_FID_READSUB,
  PIPLX_FID_SETMODE,
  PIPLX_FID_SETTLETIME,
  PIPLX_FID_STATUS,
  PIPLX_FID_SUBINFO,
  PIPLX_FID_SUBSTATUS,
  PIPLX_FID_SUBTYPE,
  PIPLX_FID_VERSION,
  PIPLX_FID_VIEWBIT,
  PIPLX_FID_VIEWCROSSPOINT,
  PIPLX_FID_VIEWMASK,
  PIPLX_FID_VIEWMASKBIT,
  PIPLX_FID_VIEWMASKCROSSPOINT,
  PIPLX_FID_VIEWSUB,
  PIPLX_FID_WRITECAL,
  PIPLX_FID_WRITEMASK,
  PIPLX_FID_WRITESUB,
  PIPLX_FID_ATTENTYPE,
  PIPLX_FID_ATTENINFO,
  PIPLX_FID_ATTENSETATTENUATION,
  PIPLX_FID_ATTENGETATTENUATION,
  PIPLX_FID_ATTENPADVALUE,
  PIPLX_FID_PSUTYPE,
  PIPLX_FID_PSUINFO,
  PIPLX_FID_PSUSETVOLTAGE,
  PIPLX_FID_PSUGETVOLTAGE,
  PIPLX_FID_PSUENABLE,
  PIPLX_FID_SUBATTRIBUTE,
  PIPLX_FID_OPSWITCH,
  PIPLX_FID_COUNTFREECARDS,
  PIPLX_FID_FINDFREECARDS,
	PIPLX_FID_OPENCARDSFORREAD,
	PIPLX_FID_OPENSPECIFIEDCARDFORREAD,
  PIPLX_FID_WRITECALFP,
  PIPLX_FID_READCALFP,
  PIPLX_FID_WRITECALDATE,
  PIPLX_FID_READCALDATE,
  PIPLX_FID_RESSETRESISTANCE,
  PIPLX_FID_RESGETRESISTANCE,
  PIPLX_FID_SETCALPOINT,
  PIPLX_FID_RESINFO,
  // BIRST
  PIPLX_FID_BIRSTCAPABILITIES,
  PIPLX_FID_BIRSTINFO,
  PIPLX_FID_BIRSTSETCONTROLS,
  PIPLX_FID_BIRSTGETCONTROLS,
  PIPLX_FID_BIRSTMEASUREMENT,
  PIPLX_FID_BIRSTWRITECAL,
  PIPLX_FID_BIRSTREADCAL,
  PIPLX_FID_BIRSTWRITECALDATE,
  PIPLX_FID_BIRSTREADCALDATE,  
  // Battery Simulator
  PIPLX_FID_BATTSETVOLTAGE,
  PIPLX_FID_BATTGETVOLTAGE,
  PIPLX_FID_BATTSETCURRENT,
  PIPLX_FID_BATTGETCURRENT,
  PIPLX_FID_BATTSETENABLE,
  PIPLX_FID_BATTGETENABLE,
  PIPLX_FID_BATTREADINTERLOCKSTATE,
  // Vsource
  PIPLX_FID_VSOURCESETRANGE,
  PIPLX_FID_VSOURCEGETRANGE,
  PIPLX_FID_VSOURCESETVOLTAGE,
  PIPLX_FID_VSOURCEGETVOLTAGE,
  PIPLX_FID_VSOURCESETENABLE,
  PIPLX_FID_VSOURCEGETENABLE,
  // Aditional BIRST
  PIPLX_FID_BIRSTATTRIBUTE,
  PIPLX_FID_BIRSTSETCONTROLSEX,
  PIPLX_FID_BIRSTGETCONTROLSEX,

  // Only for compatibility with ServerBridge
  PIPLX_FID_ERRORMESSAGE,
  // Aditional for CERN
  PIPLX_FID_GETSTATUSMESSAGE
};

#endif // _FIDS_H_
