# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

all clean cleanall:

HEADERS_LIST=\
	cvorb.h \
	libcvorb.h \

# use default instalation rule for headers
install: install_headers_global
