CPU?=L866
include $(M)/../../common.mk
# Uncomment line below when build env supports it
#include /acc/dsc/src/co/Make.auto

ccflags-y += -I$(M)/../../tpci200/include
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"

obj-m := ipoctal.o
ipoctal-objs := ipoctal_drvr.o 


