# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

all clean cleanall:

HEADERS_LIST=\
	libvmod12a22dioaio.h \
	libvmod12a2.h \
	libvmod12a4.h \
	libvmod12e162dioaio.h \
	libvmod12e16.h \
	libvmod16a22dioaio.h \
	libvmod16a2.h \
	libvmoddor2dioaio.h \
	libvmoddor.h \
	libvmod.h \
	libvmodttl2dioaio.h \
	libvmodttl.h \

# use default instalation rule for headers
install: install_headers_global
