ccflags-y += -g -Wall
ccflags-y += -Wstrict-prototypes
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"
ccflags-y += -I$(M)/../include
ccflags-y += -I$(M)/../../vmebridge/include

obj-m += cvorb.o

cvorb-objs := cvorb_func.o cvorb_sysfs.o cvorb_drvr.o cvorb_dma.o
