CPU?=L866
include $(M)/../../common.mk
# Uncomment line below when build env supports it
#include /acc/dsc/src/co/Make.auto

ccflags-y += -g -Wall
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"
ccflags-y += -Wstrict-prototypes
ccflags-y += -I$(M)
ccflags-y += -I $(M)/../include
ccflags-y += -I /acc/src/dsc/drivers/coht/vmebridge/include

obj-m += cvorb.o

cvorb-objs := cvorb_func.o cvorb_sysfs.o cvorb_drvr.o cvorb_dma.o
