# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	cvorg.awk \
	install_cvorg.sh \

# use default instalation rule for headers
install: install_scripts_global
