# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	install_msatt.sh \
	luns.awk \
	transfer2insmod.awk \

# use default instalation rule for headers
install: install_scripts_global
