# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	install_vd80.sh \
	vd80-2.awk \

# use default instalation rule for headers
install: install_scripts_global
