# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	sis3300inst.sh \
	sis3302inst.sh \
	sis3320inst.sh \
	sis33inst.pl \

# use default instalation rule for headers
install: install_scripts_global
