/*******************************************************************************
 *  Pickering pi743 functions IDs
 *
 *  Copyright (C) 1988 - 2011, Pickering Interfaces ltd.
 *  
 *  Author: petr.sojnek
 *  Contact: petr.sojnek@pickeringmail.cz
 *  
 *******************************************************************************/

#ifndef __FIDS_H__
#define __FIDS_H__

enum Pi743lxFunctionIDs {
	PI743LX_FID_CLEAROVERCURRENTSTATUS = 0X00030000,
	PI743LX_FID_CLEARTRIGGERSTATUS,
	PI743LX_FID_CLOSE,
	PI743LX_FID_ERRORMESSAGE,
	PI743LX_FID_GETADDRESSCOUNTER,
	PI743LX_FID_GETCLOCKDIVIDER,
	PI743LX_FID_GETMEASUREDOUTPUTCURRENT,
	PI743LX_FID_GETMEASUREDOUTPUTVOLTAGE,
	PI743LX_FID_GETOUTPUTALL,
	PI743LX_FID_GETOUTPUTCONNECTION,
	PI743LX_FID_GETOUTPUTCURRENTLIMIT,
	PI743LX_FID_GETOUTPUTVOLTAGE,
	PI743LX_FID_GETOVERCURRENTSTATUS,
	PI743LX_FID_GETPOWERSUPPLYSTATUS,
	PI743LX_FID_GETTRIGGER,
	PI743LX_FID_GETTRIGGERCURRENT,
	PI743LX_FID_GETTRIGGERSTATUS,
	PI743LX_FID_GETTRIGGERVOLTAGE,
	PI743LX_FID_INIT,
	PI743LX_FID_MEMORYTEST,
	PI743LX_FID_READCAPTUREDCURRENT,
	PI743LX_FID_READCAPTUREDVOLTAGE,
	PI743LX_FID_READCURRENTCALVALUES,
	PI743LX_FID_READID,
	PI743LX_FID_READMAXIMUMPOWER,
	PI743LX_FID_READVOLTAGECALVALUES,
	PI743LX_FID_RESET,
	PI743LX_FID_SELFTEST,
	PI743LX_FID_SETADDRESSCOUNTER,
	PI743LX_FID_SETCLOCKDIVIDER,
	PI743LX_FID_SETOUTPUTALL,
	PI743LX_FID_SETOUTPUTCONNECTION,
	PI743LX_FID_SETOUTPUTCURRENTLIMIT,
	PI743LX_FID_SETOUTPUTVOLTAGE,
	PI743LX_FID_SETPOWERSUPPLYSTATUS,
	PI743LX_FID_SETSOFTWARETRIGGER,
	PI743LX_FID_SETTRIGGER,
	PI743LX_FID_SETTRIGGERCURRENT,
	PI743LX_FID_SETTRIGGERVOLTAGE,
	PI743LX_FID_STORECURRENTCALVALUES,
	PI743LX_FID_STOREVOLTAGECALVALUES,
	PI743LX_FID_WRITEMAXIMUMPOWER,
	PI743LX_FID_FINDINSTRUMENTS,
	PI743LX_FID_FINDINSTRUMENTSRSRC,
	PI743LX_FID_ISSTABILIZED,
	PI743LX_FID_WAITFORSTABILIZED,
	PI743LX_FID_WRITEID,
	PI743LX_FID_WRITEMEMORY,
	PI743LX_FID_READADC,
	PI743LX_FID_READCURRENTDAC,
	PI743LX_FID_READEEPROM,
	PI743LX_FID_READOUTPUTDAC,
	PI743LX_FID_READREGISTER,
	PI743LX_FID_WRITECURRENTDAC,
	PI743LX_FID_WRITEEEPROM,
	PI743LX_FID_WRITEOUTPUTDAC,
	PI743LX_FID_WRITEREGISTER,
	PI743LX_FID_VERSION,
	/* ------ ONLY FOR LXI ACCESS ----- */
	PI743LX_FID_INITCARDFORREAD,
	PI743LX_FID_INITCARDSFORREAD
};

#endif // __FIDS_H__
