#!/bin/sh

echo "======================================================="
echo "install CTRP/I driver ../ctrp/ctrp.ko                  "
echo "install No xml file will be used                       "
echo "install This is a light weight installer for tests only"
echo "======================================================="

/sbin/insmod ./ctrp.ko

MAJOR=`cat /proc/devices | awk '{if ($2 == "ctrp") printf $1}'`
echo Making nodes for ${MODULE} major device ctr ${MAJOR}
if [ -z "$MAJOR" ]; then
        echo "driver ctr not installed !"
        exit 2
fi
rm -f /dev/ctr.1
/bin/mknod  -m 0666 /dev/ctr.1 c ${MAJOR} 1
