CPU?=L866
include $(M)/../../common.mk
# Uncomment line below when build env supports it
#include /acc/dsc/src/co/Make.auto

ccflags-y += -I$(M)/../../vmebridge/driver
ccflags-y += -I$(M)/../include

obj-m 	     := tvme200.o
tvme200-objs := carrier_tvme200.o 
