#!/bin/awk -f

BEGIN {
   format = "%Y %a %B-%e %H:%M:%S";
   print "";
   print "# This ctim list was generated by gcrap.awk at:" strftime(format)
   print ""

   ctims = 0;
   ctim[1024];

}

{
   if ($1 == "{CTIM") {
      found = 0;
      for (i=0; i<ctims+1; i++) {
	 if (ctim[i] == $2) {
	    found = 1;
	    break;
	 }
      }

      if (found == 0) {
	 ctim[ctims] = $2;
	 if (ctims < 1023) {
	    ctims = ctims + 1;
	    print $2;
	 }
      }
   }
}

END {
   print ""
   print "# Found: " ctims " Ctims"
}
