//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Picmlx.rc
//
#define RES_PICMLX_CLI_INVALID_SESSION  101
#define RES_PICMLX_CLI_HOST_UNAVAILABLE 102
#define RES_PICMLX_CLI_CONNECT          103
#define RES_PICMLX_CLI_PARAM_SIZE       104
#define RES_PICMLX_CLI_BEGINTRANS       105
#define RES_PICMLX_CLI_ENDTRANS         106
#define RES_PICMLX_CLI_RECV_FAILED      107
#define RES_PICMLX_CLI_RECV_DATA        108
#define RES_PICMLX_CLI_SEND_FAILED      109
#define RES_PICMLX_CLI_NOT_CONNECTED    110
#define RES_PICMLX_CLI_INVALID_INDEX    111
#define RES_PICMLX_CLI_DIRECTECHO_FAILED 112
#define RES_PICMLX_CLI_BROADCASTECHO_FAILED 113
#define RES_PICMLX_CLI_FUNC_NOT_LOCAL   114
#define RES_PICMLX_CLI_DATA_NOT_ACCEPTABLE 115
#define RES_PICMLX_CLI_DATA_NOT_ACCEPT  115
#define RES_PICMLX_CLI_CONNECT_REFUSED  116
#define RES_PICMLX_CLI_NAME_NOT_KNOWN   117
#define RES_PICMLX_SRV_INVALID_FID      201
#define RES_PICMLX_SRV_RPC_DATA         202
#define RES_PICMLX_SRV_INVALID_CARDID   203
#define RES_PICMLX_SRV_INVALID_ADDRESS  204
#define RES_PICMLX_SRV_OPEN_CARD        205
#define RES_PICMLX_SRV_ACCESS_DENIED    206
#define RES_PICMLX_SRV_NOT_SUPPORTED    207
#define RES_PICMLX_SRV_DEVICE_INFO      208
#define RES_PICMLX_SRV_OUT_OF_RESOURCES 209
#define RES_PICMLX_SRV_DATA_LENGTH      210
#define RES_PICMLX_SRV_CARD_TYPE        211
#define RES_PICMLX_SRV_FUNC_NOT_IMPL    212
#define RES_PICMLX_SRV_CARD_USED_BYCLI  213
#define RES_PICMLX_SRV_UNDEFINED        214
#define RES_PICMLX_SRV_WAIT_TIMEOUT     215
#define RES_PICMLX_SRV_DEVICE_LOCKED    216
#define RES_PICMLX_SRV_INVALID_SESSION  217
#define RES_PICMLX_SRV_INVALID_TOKEN    218
#define RES_PICMLX_SRV_INVALID_EC       219
#define RES_PICMLX_SRV_FATAL_01         220
#define RES_PICMLX_SRV_ONLY_ADLINK_SUPPORTED 221
#define RES_PICMLX_CLI_TIMEOUT_FAIL     222
#define RES_UNKNOWN_ERROR               300
#define RES_NO_ERROR                    301

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
