/*******************************************************************************
*  ServeBridge special functions IDs
*
*  Copyright (C) 1988 - 2011, Pickering Interfaces ltd.
*  
*  Author: michal.heczko
*  Contact: michal.heczko@pickeringmail.cz 
*  
*******************************************************************************/

#ifndef _PICMLXFIDS_H_
#define _PICMLXFIDS_H_

enum ServerFunctionsFids {
    PICMLX_FID_SB_VERSION = 0x000F0000,
    PICMLX_FID_SB_RESET,
    PICMLX_FID_SB_INFO,
    PICMLX_FID_SB_CARDCOUNTTYPE,
    PICMLX_FID_SB_LOCK,
    PICMLX_FID_SB_UNLOCK,
    PICMLX_FID_SB_LOCAL_EVENT,
    PICMLX_FID_GET_TOTAL_CARDS_COUNT,
    PICMLX_FID_GET_TOTAL_OPENED_CARDS,
    PICMLX_FID_GET_TOTAL_MODULES_COUNT,
    PICMLX_FID_GET_SESSIONS_COUNT,
    PICMLX_FID_GET_SESSIONS_BY_CARD,
    PICMLX_FID_USE_ANOTHER_SESSION,
    PICMLX_FID_RELEASE_ANOTHER_SESSION,
    PICMLX_FID_RELEASE_FOR_USE,
    PICMLX_FID_USE_CARD,
    PICMLX_FID_USE_CARDS,
    PICMLX_FID_RELEASE_CARD,
    PICMLX_FID_RELEASE_CARDS,
    PICMLX_FID_HAS_EXCLUSIVE_ACCESS,
    PICMLX_FID_IS_CARD_USED,
    PICMLX_FID_GET_CONNECTED_HOSTS,
    PICMLX_FID_GET_CONNECTED_CARD_HOSTS,
    PICMLX_FID_GET_USED_CARDS,
    PICMLX_FID_GET_USABLE_CARDS,
    PICMLX_FID_GET_FOREIGN_SESSIONS,
    PICMLX_FID_GET_EMFROMEC,
    PICMLX_FID_GET_ALL_SESSIONS,
    PICMLX_FID_KILL_SESSION,
	PICMLX_FID_GET_CHASSIS_VOLTAGES,
	PICMLX_FID_GET_CHASSIS_TEMPERATURES,
	PICMLX_FID_GET_CHASSIS_FANSPEEDS,
	PICMLX_FID_SET_CHASSIS_FANSPEEDS,
	PICMLX_FID_POWER_CYCLE,
	PICMLX_FID_IDENTIFY,
	PICMLX_FID_STORESTATES
};

#endif // _FIDS_H_
