obj-m += pickeringmuxdrv.o
pickeringmuxdrv-objs += pickeringmuxmain.o
pickeringmuxdrv-objs += pickering16to16.o
pickeringmuxdrv-objs += pickering16to16a.o
pickeringmuxdrv-objs += pickering4to1.o
pickeringmuxdrv-objs += pickering9to8.o
pickeringmuxdrv-objs += pickering22to8.o
pickeringmuxdrv-objs += pickeringattn.o
ccflags-y += -g -Wall
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"

