CPU?=L866
include $(M)/../../common.mk
# Uncomment line below when build env supports it
#include /acc/dsc/src/co/Make.auto

ccflags-y = -g -Wall
ccflags-y += -I$(M)/../../vmebridge/include
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"

obj-m += modulbus_register.o 
obj-m += mod-pci.o vmodio.o 
obj-m += vmodttl.o vmoddor.o vmod12a2.o vmod12a4.o
obj-m += vmod12e16.o vmod16a2.o
obj-m += vmodttl.o 

vmoddor-objs := lunargs.o vmoddordrvr.o
vmod12a2-objs := lunargs.o vmod12a2drvr.o
vmod12a4-objs := lunargs.o vmod12a4drvr.o
vmod12e16-objs := lunargs.o vmod12e16drvr.o
vmod16a2-objs := lunargs.o vmod16a2drvr.o
vmodttl-objs := lunargs.o vmodttldrvr.o
