ccflags-y += -g -Wall
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"
ccflags-y += -I$(M)/../include
ccflags-y += -I$(M)/../../vmebridge/include

obj-m += cvorg.o

cvorg-objs := cvorg-func.o cvorg_sysfs.o clkgen.o cvorgdrv.o 
