CPU?=L866
include $(M)/../../common.mk
# Uncomment line below when build env supports it
#include /acc/dsc/src/co/Make.auto

ccflags-y += -g -Wall
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"
ccflags-y += -I$(M)/../include
ccflags-y += -I$(M)/../../vmebridge/include

obj-m += cvorg.o

cvorg-objs := cvorg-func.o cvorg_sysfs.o clkgen.o cvorgdrv.o 
