# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	icv196.awk \
	install_icv196_linux.sh \
	install_icv196.sh \
	icv196vmeinstall \

# use default instalation rule for headers
install: install_scripts_global
