# include the build environment
include ../../common.mk

#include version information
include ../versions.mk

# empty rules
all clean cleanall:

SCRIPTS_LIST=\
	modpci_install.pl \
	vmod12a2_inst.sh \
	vmod12a4_inst.sh \
	vmod12e16_inst.sh \
	vmod16a2_inst.sh \
	vmoddor_inst.sh \
	vmod_install.pl \
	vmodio_install.pl \
	vmodio_inst.sh \
	vmodttl_inst.sh \

# use default instalation rule for headers
install: install_scripts_global
